# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: maildom-kisumu

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  profile: bignorth

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.email
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: main
          method: get
          cors: true
